name: Server build test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      working-directory: ./server
      run: make
    - name: make clean install
      working-directory: ./server
      run: sudo make clean install
    - name: make clean ndinstall
      working-directory: ./server
      run: sudo make clean ndinstall
    - name: make debug
      working-directory: ./server
      run: make debug
